sources:
  - Sources/TARGET_NAME/
  - Pods/
templates:
  # - Sources/TARGET_NAME/
  # - Pods/Sourcery/Templates/AutoEquatable.stencil
  # - Pods/XCEToolbox/Templates/Common/ConcurrentProcess.stencil
  - Pods/XCEToolbox/Templates/iOS/App.stencil
  # - Pods/XCEToolbox/Templates/iOS/AutoOnScreenFeature.stencil
  # - Pods/XCEToolbox/Templates/iOS/VisualFeature_Ctrl.stencil
  # - Pods/XCEToolbox/Templates/iOS/VisualFeature_View.stencil
  # - Pods/XCEToolbox/Templates/iOS/VisualFeatureNoView_Ctrl.stencil

output:
  Sources/TARGET_NAME/_Auto/
